name: CI Pipeline

on:
  pull_request:
    branches:
      - Feather
      - Develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print working directory
        run: pwd

      - name: List files in current directory
        run: ls -al

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "package.json not found in current directory!"
            exit 1
          fi

      - name: Run tests
        run: npm test
